//stack
export const SPLASH_STACK = 'SPLASH_STACK';
export const ROOT_STACK = 'ROOT_STACK';

//drawer
export const DRAWER_NAVIGATION = 'DRAWER_NAVIGATION';
export const PAYMENT_SCREEN = 'PAYMENT_SCREEN';
export const HISTORY_SCREEN = 'HISTORY_SCREEN';
export const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN';
export const INVITE_FRIEND_SCREEN = 'INVITE_FRIEND_SCREEN';
export const SETTINGS_SCREEN = 'SETTINGS_SCREEN';

export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const SIGN_UP_SCREEN = 'SIGN_UP_SCREEN';
export const SIGN_IN_SCREEN = 'SIGN_IN_SCREEN';
export const COMPLETE_STEP_SCREEN = 'COMPLETE_STEP_SCREEN';
export const ENTER_CODE_SCREEN = 'ENTER_CODE_SCREEN';

//map-view
export const MAP_VIEW_SCREEN = 'MAP_VIEW_SCREEN';
